-- CreateTable
CREATE TABLE "vessels" (
    "Name" TEXT NOT NULL,
    "IMONo" INTEGER NOT NULL,
    "vessel_type" INTEGER NOT NULL,

    CONSTRAINT "vessels_pkey" PRIMARY KEY ("IMONo")
);

-- CreateTable
CREATE TABLE "references" (
    "RowID" SERIAL NOT NULL,
    "Category" TEXT NOT NULL,
    "VesselTypeID" INTEGER NOT NULL,
    "Size" TEXT NOT NULL,
    "Traj" TEXT NOT NULL,
    "a" DOUBLE PRECISION NOT NULL,
    "b" DOUBLE PRECISION NOT NULL,
    "c" DOUBLE PRECISION NOT NULL,
    "d" DOUBLE PRECISION NOT NULL,
    "e" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "references_pkey" PRIMARY KEY ("RowID")
);

-- CreateTable
CREATE TABLE "daily_logs" (
    "eid" SERIAL NOT NULL,
    "VesselID" INTEGER NOT NULL,
    "LOGID" INTEGER NOT NULL,
    "FromUTC" TIMESTAMP(3) NOT NULL,
    "TOUTC" TIMESTAMP(3) NOT NULL,
    "MET2WCO2" DOUBLE PRECISION NOT NULL,
    "AET2WCO2" DOUBLE PRECISION NOT NULL,
    "BOT2WCO2" DOUBLE PRECISION NOT NULL,
    "VRT2WCO2" DOUBLE PRECISION NOT NULL,
    "TotT2WCO2" DOUBLE PRECISION NOT NULL,
    "MEW2WCO2e" DOUBLE PRECISION NOT NULL,
    "AEW2WCO2e" DOUBLE PRECISION NOT NULL,
    "BOW2WCO2e" DOUBLE PRECISION NOT NULL,
    "VRW2WCO2e" DOUBLE PRECISION NOT NULL,
    "ToTW2WCO2" DOUBLE PRECISION NOT NULL,
    "MESox" DOUBLE PRECISION NOT NULL,
    "AESox" DOUBLE PRECISION NOT NULL,
    "BOSox" DOUBLE PRECISION NOT NULL,
    "VRSox" DOUBLE PRECISION NOT NULL,
    "TotSOx" DOUBLE PRECISION NOT NULL,
    "MENOx" DOUBLE PRECISION NOT NULL,
    "AENOx" DOUBLE PRECISION NOT NULL,
    "TotNOx" DOUBLE PRECISION NOT NULL,
    "MEPM10" DOUBLE PRECISION NOT NULL,
    "AEPM10" DOUBLE PRECISION NOT NULL,
    "TotPM10" DOUBLE PRECISION NOT NULL,
    "AERCO2T2W" DOUBLE PRECISION NOT NULL,
    "AERCO2eW2W" DOUBLE PRECISION NOT NULL,
    "EEOICO2eW2W" DOUBLE PRECISION NOT NULL,
    "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "daily_logs_pkey" PRIMARY KEY ("eid")
);

-- CreateIndex
CREATE UNIQUE INDEX "daily_logs_LOGID_key" ON "daily_logs"("LOGID");

-- AddForeignKey
ALTER TABLE "daily_logs" ADD CONSTRAINT "daily_logs_VesselID_fkey" FOREIGN KEY ("VesselID") REFERENCES "vessels"("IMONo") ON DELETE RESTRICT ON UPDATE CASCADE;
